# Generated by Django 3.2 on 2021-04-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=12)),
                ('telegram', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('pre_context', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('published', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
