# Generated by Django 3.2 on 2021-04-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210426_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedetail',
            old_name='site_tite',
            new_name='site_title',
        ),
    ]
