# Generated by Django 3.2 on 2021-04-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_site_tite_sitedetail_site_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteDetail',
        ),
    ]
