# Generated by Django 3.2 on 2021-04-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_sitedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ دسته بندی')),
                ('status', models.BooleanField(default=True, max_length=100, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'درباره من', 'verbose_name_plural': 'درباره من'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-create_date',), 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterField(
            model_name='article',
            name='context',
            field=models.TextField(verbose_name='محتوای اصلی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='تصویر مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pre_context',
            field=models.CharField(max_length=255, verbose_name='پیش مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='تیتر'),
        ),
        migrations.AddField(
            model_name='article',
            name='catgory',
            field=models.ManyToManyField(to='core.Category', verbose_name='دسته بندی'),
        ),
    ]
